### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by spruill7716** [MrIbby/BabyAnimals#2]
I'm trying to start-up my Cauldron 1.7.10 server with this mod but I seem to be getting this crash:
https://www.dropbox.com/s/bhut9jtojtoqe1b/crash-2015-03-03_18.04.45-server.txt?dl=0

**Comment by MrIbby** [comment]
This is a client-side mod :P

**Comment by MrIbby** [comment]
Fixed in:
* [Baby Animals Model Swapper 1.11](https://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2347490)
* [Baby Animals Model Swapper 1.9.4, Update 2](https://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2437286)
* [Baby Animals Model Swapper 1.8.9, Update 2](https://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2437284)
* [Baby Animals Model Swapper 1.7.10, Update 4](https://minecraft.curseforge.com/projects/baby-animals-model-swapper/files/2437280)
